  redis:
    url: "localhost:6379"
    # username: ""
    # password: ""
    graphname: "AREA"

# Example data 
#
# area.csv
#     areas, with foreign key to area_category.csv
# area_category.csv
#   area_categories
#
# Example maps files as:
#   (:area{area_id, area_category_id, active_from, active_from}) -[:address_category]-> (:address_category{area_category_id, name})
#
  files:
    - filename: "/Users/seponr/Dropbox/redisgraph-bulkinsert/examples/area_category.csv"
      separator: ";"
      header: true
      columns:       
        - "area_category_id"     
        - "name"
      nodes:
        AreaCategory:
          # filters:
          #  - "area_category_id < 3"
          properties:
            - colname: "area_category_id"
              type: "numeric"
            - colname: "name"
              type: "string"       

    - filename: "/Users/seponr/Dropbox/redisgraph-bulkinsert/examples/area.csv"
      separator: ";"
      header: true
      columns:
        - "area_id"
        - "area_category_id"
        - "name"
        - "active_from"
        - "active_to"
      nodes:      
        Area:
          properties:
            - colname: "area_id"
              type: "numeric"
            - colname: "area_category_id"
              type: "numeric"
            - colname: "active_from"
              type: "string"              
            - colname: "active_to"
              type: "string"                             
      edges:
        Area_Category:
          src: 
            label: "area"
            value: "area_id"
          dst:
            label: "areaCategory"
            value: "area_category_id"        


    


